# .streamlit/secrets.toml
GOOGLE_API_KEY = "AIzaSyAtDv7PxOYKOMSSZVouCqEEXx8KpwGPe2E"
DATABASE_URL = "postgresql://neondb_owner:npg_PJBv6xb5KjtX@ep-ancient-resonance-a1any7dc-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"